

# This file was *autogenerated* from the file bin_LFSR.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_15 = Integer(15); _sage_const_37 = Integer(37)
def q_ary_lfsr(seed, taps, constants, q, length):
    """
    A function to simulate a q-ary LFSR.
    
    :param seed: Initial state of the LFSR (list of integers)
    :param taps: Positions that affect the feedback (list of integers)
    :param constants: Multiplicative constants for each tap (list of integers)
    :param q: Base of the LFSR (integer)
    :param length: Length of the sequence to generate
    :return: Generated LFSR sequence (list of integers)
    """
    # Initialize the register with the seed
    register = seed[:]
    output = []

    # Generate the sequence
    for _ in range(length):
        # Calculate the feedback bit as generalized XOR (mod-q addition) of the tapped positions
        feedback = sum(register[taps[i]] * constants[i] for i in range(len(taps))) % q
        # Output the bit at the last position
        output.append(register[-_sage_const_1 ])
        # Shift all bits, and place the feedback bit at the front
        register = [feedback] + register[:-_sage_const_1 ]

    return output

# Example usage for q = 2, similar to the binary LFSR example above
q = _sage_const_2 
seed = [_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ]
taps = [_sage_const_0 , _sage_const_3 ]
constants = [_sage_const_1 , _sage_const_1 ]  # Since q = 2, the constants are still 1 (like binary feedback)
sequence_q2 = q_ary_lfsr(seed, taps, constants, q, _sage_const_15 )
print("Generated q-ary LFSR sequence for q=2 :", sequence_q2)

# Now test for q = 37 with the same configuration but different constants
q = _sage_const_37 
constants = [_sage_const_1 , _sage_const_1 ]  # Example constants for demonstration
sequence_q37 = q_ary_lfsr(seed, taps, constants, q, _sage_const_15 )
print("Generated q-ary LFSR sequence for q=37:", sequence_q37)

